feat(PLA-517): update user welcome profile text
Mind-Sports-Games/lila pull request #760
Opened 2024-04-23 07:27 UTC by vincentfrochot

2024-04-23 08:08 UTC, JamesHeppell requested changes
Looks good, I suggest we could use the translations module instead of strings here to better support all languages for the future, you could also add in the French version. 
The lichess code base has example for this (adding a new onboarding file for the set of translations). They have deviated from the setup we/they had, so best to copy the design for 'trans' we have, e.g. in app/views/user/show/side.scala, or app/views/user/show/header.scaka (using trans.<name of translation>() )
Translations are stored in their respective folder:
source provides the default version (english)
dest provides the languages, we usually fill out the en-us.xml but you can also do fr-FR.xml (i assume is french). Matt is in the process of supporting the translation service to keep up to date with all the other languages and kind support from the community.
The keys are set in module/i19n/src/main/I18vkeys.scala 
Quite a bit of code should overlap with what we have and/or lichess.

2024-04-23 08:25 UTC, msomatt commented
Agree with James' review. Great that we get French translations for free now!

2024-04-24 07:03 UTC, vincentfrochot commented
![Screenshot from 2024-04-24 09-01-48](https://github.com/Mind-Sports-Games/lila/assets/223244/ec4428bf-c253-4adc-86fd-fa2c2752ae97)
![Screenshot from 2024-04-24 09-01-30](https://github.com/Mind-Sports-Games/lila/assets/223244/110632ce-ed85-47bd-b4c4-08a12adfcf1d)
![Screenshot from 2024-04-24 08-58-53](https://github.com/Mind-Sports-Games/lila/assets/223244/90c721ce-d52b-44e3-a1c7-8857b0eb2240)

2024-04-24 07:50 UTC, JamesHeppell approved these changes

2024-04-24 07:54 UTC, merged